language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer selfupdate
  - composer install
  - mysql -e 'create database `test-timestamp-migrations`;'

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
